name: Error
description: You need help resolving an error/crash in the converter
body:
  - type: dropdown
    attributes:
      label: What is the preset selected?
      options:
        - Charts only
        - Songs only
        - Characters only
        - Stages only
        - Full mod
        - I chose

  - type: dropdown
    attributes:
      label: What platform?
      options:
        - Windows
        - Mac
        - Linux (Ubuntu)

  - type: textarea
    attributes:
      label: What are the contents of the latest .log file? You can find them in your logs folder, next to the EXE.

  - type: textarea
    attributes:
      label: What are the contents of your mod folder?

  - type: textarea
    attributes:
      label: Additional Context

  - type: checkboxes
    attributes:
      label: Issue Checklist
      options:
        - label: I have properly named the issue
        - label: I looked in issues/discussions, if my question was previously anwsered

# based on https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/.github/ISSUE_TEMPLATE/api_error.yml